<?php
define('SET_OWNER','Ueppy srl');
define('SET_OFFLINE','1');
define('SET_GOOGLE_MAPS_KEY','AIzaSyDSy8WA5MvaOaHFJpB6qUMLYdPh6K339Tg');
define('SET_URCHIN_GOOGLE_CODE','');
define('SET_IMGHEAD','/images/site/logo.png');
define('SET_LANGUAGES','it');
define('SET_ITEMS_PER_PAGE','15');
define('SET_SOCIAL_FLICKR','http://flickr.com/');
define('SET_SMTP_HOST','');
define('SET_SMTP_PASSWORD','');
define('SET_SMTP_USER','');
define('SET_EMAIL_SENDER','info@ueppy.com');
define('SET_SENDER_NAME','www.ueppy.com');
define('SET_ACCEPTED_EXT','pdf,jpg,jpeg,png,gif,pps,ppt,doc');
define('SET_TITLE','Ueppy CMS');
define('SET_KEYWORDS','test');
define('SET_DESCRIPTION','Description Meta TAG');
define('SET_ELEMENTI_HTML_CONSENTITI','a[href],strong,i,em,li,ol,ul,blockquote,br');
define('SET_PAGINE_IMG_ALLOWED','1');
define('SET_PAGINE_FILES_ALLOWED','1');
define('SET_PAGINE_IMG_SIZE','1500x500|crop|loss');
define('SET_EMAILS_FORM_CONTATTO','gianiaz@gmail.com;gianiaz@gianiaz.net');
define('SET_EMAIL_COMMENTI','gianiaz@gmail.com');
define('SET_PAGINE_NIMG_LIMIT','20');
define('SET_RISULTATI_SE','2');
define('SET_PAGINA_COME_CAT','1');
define('SET_ESTENSIONI_VIETATE','php,phtml,sh,php3,com,ruby,sh,asp,html');
define('SET_DIMENSIONI_IMMAGINI_ESTENSIONI','16x16px');
define('SET_FM_MAX_MB_TOTAL','200');
define('SET_FM_MAX_FILE_SIZE','150');
define('SET_SOCIAL_INSTAGRAM','http://www.instagram.com/');
define('SET_MAX_NUM_OF_FILE_QUEUE','2');
define('SET_CLIENT_CAN_DELETE','0');
define('SET_ENABLE_LIKES','1');
define('SET_FB_APP_SECRET','5bab05fc5c1bc6565e3b4869a6f303d1');
define('SET_FB_APP_ID','1125905460812911');
define('SET_ENABLE_ECOMMERCE','0');
define('SET_IUBENDA_POLICY_IDS','');
define('SET_DC_MAX_DEPTH','5');
define('SET_SOCIAL_RSS','http://iterme/rss.xml');
define('SET_GOOGLE_ANALYTICS_PROFILE_ID','32345657');
define('SET_SOCIAL_SKYPE','skype');
define('SET_COMMENTO_STATO_DEFAULT','1');
define('SET_PRIVACY_ID_INTERNA','275');
define('SET_PAGINE_COMMENTI','1');
define('SET_DEFAULT_LANG','it');
define('SET_ORDINI_BCC','gianiaz@gmail.com');
define('SET_COMMENTI_STATO_DEFAULT','1');
define('SET_SOCIAL_LINKEDIN','http://linkedin.com/');
define('SET_SOCIAL_PINTEREST','http://www.pinterest.com/');
define('SET_GOOGLE_SITE_VERIFICATION','');
define('SET_GRUPPI_ADMIN','1,3');
define('SET_ENABLE_POPUP','0');
define('SET_AUTOSAVETIME','60');
define('SET_ZRSSFEED','http://www.ueppy.com/news.rss');
define('SET_EMAILY_HOST','http://www.emaily.it');
define('SET_EMAILY_UID','44dad7489476ce');
define('SET_EMAILY_PWD','F6hfH4pcr3');
define('SET_EMAILY_LIST','189');
define('SET_IUBENDA_SITE_ID','');
define('SET_PAGINE_NFILES_IMIT','0');
define('SET_PAGINE_DIM_INLINEA','1840x448|crop|loss-300x200|crop|loss');
define('SET_PAGINE_ELEMENTI_PAGINA','2');
define('SET_PAGINE_PAGINATORE','10');
define('SET_NUMERO_IMMAGINI_PAGINE','2');
define('SET_GEO_UPDATE_URL','http://4.ueppybox.com/media/geo/');
define('SET_SOCIAL_FACEBOOK','http://www.facebook.com/');
define('SET_SOCIAL_TWITTER','http://www.twitter.com/');
define('SET_SOCIAL_GOOGLEPLUS','http://plus.google.com/');
define('SET_SOCIAL_YOUTUBE','http://www.youtube.com/');
define('SET_SOCIAL_EMAIL','info@sito.com');
define('SET_JQUERY_UI','blitzer');
define('SET_SOCIAL_VIMEO','http://vimeo.com/');
define('SET_EMAIL_DEBUG','gianiaz@gmail.com');
define('SET_NOMESITO','www.ueppy.com');
define('SET_SERVER_SERVICE_MAIL','mail.ueppybox.com:143');
define('SET_EMAIL_PREVENTIVO','gianiaz@gmail.com');
define('SET_SMTP_SSL','1');
define('SET_QUALITY_PHOTO','70');
define('SET_TRADUZIONI_UPDATE_URL','http://4.ueppybox.com/media/traduzioni/');
define('SET_SERVICE_MAIL','service@ueppybox.com');
define('SET_SERVICE_MAIL_PWD','m$rA&ksK6fAu');
define('SET_CATEGORIA_SITO','default');
define('SET_USE_MINIFIED','1');
define('SET_SOCIAL_GITHUB','https://github.com/gianiaz/');
define('SET_NEWS_IMG_SIZE','96x72|crop-300x200|crop-600x400-800x600');
define('SET_NEWS_INTRO_MAX_CHARS','200');
define('SET_ENABLE_CAT_NEWS','0');
define('SET_NEWS_ELEMENTI_PAGINA','5');
define('SET_NEWS_COMMENTI','1');
define('SET_NEWS_IMG_ALLOWED','1');
define('SET_NEWS_FILES_ALLOWED','1');
define('SET_NEWS_NIMG_LIMIT','0');
define('SET_NEWS_NFILES_LIMIT','2');
define('SET_MODIFICA_NEWS_DI_ALTRI','0');
$sett_smarty = [];
$sett_smarty['OWNER']= 'Ueppy srl';
$sett_smarty['OFFLINE']= '1';
$sett_smarty['GOOGLE_MAPS_KEY']= 'AIzaSyDSy8WA5MvaOaHFJpB6qUMLYdPh6K339Tg';
$sett_smarty['URCHIN_GOOGLE_CODE']= '';
$sett_smarty['IMGHEAD']= '/images/site/logo.png';
$sett_smarty['LANGUAGES']= 'it';
$sett_smarty['ITEMS_PER_PAGE']= '15';
$sett_smarty['SOCIAL_FLICKR']= 'http://flickr.com/';
$sett_smarty['SMTP_HOST']= '';
$sett_smarty['SMTP_PASSWORD']= '';
$sett_smarty['SMTP_USER']= '';
$sett_smarty['EMAIL_SENDER']= 'info@ueppy.com';
$sett_smarty['SENDER_NAME']= 'www.ueppy.com';
$sett_smarty['ACCEPTED_EXT']= 'pdf,jpg,jpeg,png,gif,pps,ppt,doc';
$sett_smarty['TITLE']= 'Ueppy CMS';
$sett_smarty['KEYWORDS']= 'test';
$sett_smarty['DESCRIPTION']= 'Description Meta TAG';
$sett_smarty['ELEMENTI_HTML_CONSENTITI']= 'a[href],strong,i,em,li,ol,ul,blockquote,br';
$sett_smarty['PAGINE_IMG_ALLOWED']= '1';
$sett_smarty['PAGINE_FILES_ALLOWED']= '1';
$sett_smarty['PAGINE_IMG_SIZE']= '1500x500|crop|loss';
$sett_smarty['EMAILS_FORM_CONTATTO']= 'gianiaz@gmail.com;gianiaz@gianiaz.net';
$sett_smarty['EMAIL_COMMENTI']= 'gianiaz@gmail.com';
$sett_smarty['PAGINE_NIMG_LIMIT']= '20';
$sett_smarty['RISULTATI_SE']= '2';
$sett_smarty['PAGINA_COME_CAT']= '1';
$sett_smarty['ESTENSIONI_VIETATE']= 'php,phtml,sh,php3,com,ruby,sh,asp,html';
$sett_smarty['DIMENSIONI_IMMAGINI_ESTENSIONI']= '16x16px';
$sett_smarty['FM_MAX_MB_TOTAL']= '200';
$sett_smarty['FM_MAX_FILE_SIZE']= '150';
$sett_smarty['SOCIAL_INSTAGRAM']= 'http://www.instagram.com/';
$sett_smarty['MAX_NUM_OF_FILE_QUEUE']= '2';
$sett_smarty['CLIENT_CAN_DELETE']= '0';
$sett_smarty['ENABLE_LIKES']= '1';
$sett_smarty['FB_APP_SECRET']= '5bab05fc5c1bc6565e3b4869a6f303d1';
$sett_smarty['FB_APP_ID']= '1125905460812911';
$sett_smarty['ENABLE_ECOMMERCE']= '0';
$sett_smarty['IUBENDA_POLICY_IDS']= '';
$sett_smarty['DC_MAX_DEPTH']= '5';
$sett_smarty['SOCIAL_RSS']= 'http://iterme/rss.xml';
$sett_smarty['GOOGLE_ANALYTICS_PROFILE_ID']= '32345657';
$sett_smarty['SOCIAL_SKYPE']= 'skype';
$sett_smarty['COMMENTO_STATO_DEFAULT']= '1';
$sett_smarty['PRIVACY_ID_INTERNA']= '275';
$sett_smarty['PAGINE_COMMENTI']= '1';
$sett_smarty['DEFAULT_LANG']= 'it';
$sett_smarty['ORDINI_BCC']= 'gianiaz@gmail.com';
$sett_smarty['COMMENTI_STATO_DEFAULT']= '1';
$sett_smarty['SOCIAL_LINKEDIN']= 'http://linkedin.com/';
$sett_smarty['SOCIAL_PINTEREST']= 'http://www.pinterest.com/';
$sett_smarty['GOOGLE_SITE_VERIFICATION']= '';
$sett_smarty['GRUPPI_ADMIN']= '1,3';
$sett_smarty['ENABLE_POPUP']= '0';
$sett_smarty['AUTOSAVETIME']= '60';
$sett_smarty['ZRSSFEED']= 'http://www.ueppy.com/news.rss';
$sett_smarty['EMAILY_HOST']= 'http://www.emaily.it';
$sett_smarty['EMAILY_UID']= '44dad7489476ce';
$sett_smarty['EMAILY_PWD']= 'F6hfH4pcr3';
$sett_smarty['EMAILY_LIST']= '189';
$sett_smarty['IUBENDA_SITE_ID']= '';
$sett_smarty['PAGINE_NFILES_IMIT']= '0';
$sett_smarty['PAGINE_DIM_INLINEA']= '1840x448|crop|loss-300x200|crop|loss';
$sett_smarty['PAGINE_ELEMENTI_PAGINA']= '2';
$sett_smarty['PAGINE_PAGINATORE']= '10';
$sett_smarty['NUMERO_IMMAGINI_PAGINE']= '2';
$sett_smarty['GEO_UPDATE_URL']= 'http://4.ueppybox.com/media/geo/';
$sett_smarty['SOCIAL_FACEBOOK']= 'http://www.facebook.com/';
$sett_smarty['SOCIAL_TWITTER']= 'http://www.twitter.com/';
$sett_smarty['SOCIAL_GOOGLEPLUS']= 'http://plus.google.com/';
$sett_smarty['SOCIAL_YOUTUBE']= 'http://www.youtube.com/';
$sett_smarty['SOCIAL_EMAIL']= 'info@sito.com';
$sett_smarty['JQUERY_UI']= 'blitzer';
$sett_smarty['SOCIAL_VIMEO']= 'http://vimeo.com/';
$sett_smarty['EMAIL_DEBUG']= 'gianiaz@gmail.com';
$sett_smarty['NOMESITO']= 'www.ueppy.com';
$sett_smarty['SERVER_SERVICE_MAIL']= 'mail.ueppybox.com:143';
$sett_smarty['EMAIL_PREVENTIVO']= 'gianiaz@gmail.com';
$sett_smarty['SMTP_SSL']= '1';
$sett_smarty['QUALITY_PHOTO']= '70';
$sett_smarty['TRADUZIONI_UPDATE_URL']= 'http://4.ueppybox.com/media/traduzioni/';
$sett_smarty['SERVICE_MAIL']= 'service@ueppybox.com';
$sett_smarty['SERVICE_MAIL_PWD']= 'm$rA&ksK6fAu';
$sett_smarty['CATEGORIA_SITO']= 'default';
$sett_smarty['USE_MINIFIED']= '1';
$sett_smarty['SOCIAL_GITHUB']= 'https://github.com/gianiaz/';
$sett_smarty['NEWS_IMG_SIZE']= '96x72|crop-300x200|crop-600x400-800x600';
$sett_smarty['NEWS_INTRO_MAX_CHARS']= '200';
$sett_smarty['ENABLE_CAT_NEWS']= '0';
$sett_smarty['NEWS_ELEMENTI_PAGINA']= '5';
$sett_smarty['NEWS_COMMENTI']= '1';
$sett_smarty['NEWS_IMG_ALLOWED']= '1';
$sett_smarty['NEWS_FILES_ALLOWED']= '1';
$sett_smarty['NEWS_NIMG_LIMIT']= '0';
$sett_smarty['NEWS_NFILES_LIMIT']= '2';
$sett_smarty['MODIFICA_NEWS_DI_ALTRI']= '0';